spring:
  profiles:
    active: rabbit
debug: false

---
spring:
  profiles: rabbit
  cloud:
    stream:
      bindings:
        source :
         destination: sourceRabbit
         binder: rabbit
         group: text

      rabbit:
        binder:
#          nodes: 192.168.163.210; localhost
        bindings:
          source:
            producer:
              durableSubscription: true
              declareExchange: true
              exchangeDurable: true
              exchangeType: topic
  rabbitmq:
    host: localhost
#    username: rabbitmq
#    password: rabbitmq


server:
  port: 8081

---
spring:
  profiles: kafka
  cloud:
    stream:
      bindings:
        source :
         destination: sourceKafka
         binder: kafka
         group: text
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
          defaultZkPort: 2181
          offsetUpdateTimeWindow: 10000
          autoCreateTopics: true
          autoAddPartitions: true
          minPartitionCount: 2
          replicationFactor: 1
        producer:
          messageKeyExpression: none

#  kafka:
#    bootstrap-servers: 192.168.163.210:9092
#    zookeeper:
#      connect-string: 192.168.163.210:2181
server:
  port: 8082

---
spring:
  profiles: artemis
  cloud:
    stream:
      bindings:

        source:
          destination: jms.queue.sourceArtemis
          binder: artemis
#          group: text

        producer:
          partitionCount: 2
#          requiredGroups: text

      artemis:
        binder:
          transport: org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory

  artemis:
    mode: native
    host: localhost
    user: user
    password: password
    port: 61616

server:
  port: 8083