spring:
  profiles:
    active: rabbit

---
spring:
  profiles: rabbit
  cloud:
    stream:
      bindings:
        source :
         destination: sourceRabbit
         binder: rabbit
         group: text

      rabbit:
        binder:
#          nodes: 192.168.163.210; localhost
        bindings:
          source:
            producer:
              durableSubscription: true
              declareExchange: true
              exchangeDurable: true
              exchangeType: topic
  rabbitmq:
    host: 192.168.163.210
    password: rabbitmq
    username: rabbitmq


server:
  port: 8081

---
spring:
  profiles: kafka
  cloud:
    stream:
      bindings:
        source :
         destination: sourceKafka
         binder: kafka
         group: text
      kafka:
        binder:
          brokers: 192.168.163.210
          defaultBrokerPort: 9092
          zkNodes: 192.168.163.210
          defaultZkPort: 2181
          offsetUpdateTimeWindow: 10000
          autoCreateTopics: true
          autoAddPartitions: true
          minPartitionCount: 2
          replicationFactor: 1
        producer:
          messageKeyExpression: none

#  kafka:
#    bootstrap-servers: 192.168.163.210:9092
#    zookeeper:
#      connect-string: 192.168.163.210:2181
server:
  port: 8082

---
spring:
  profiles: artemis
  cloud:
    stream:
      bindings:
        source :
         destination: sourceArtemis
         binder: artemis
         group: text
      artemis:
        binder:
          brokers: localhost; 192.168.163.210
          defaultBrokerPort: 9092
          zkNodes: localhost; 192.168.163.210
          defaultZkPort: 2181
          offsetUpdateTimeWindow: 10000
        producer:
          messageKeyExpression: none

#  kafka:
#    bootstrap-servers: 192.168.163.210:9092
#    zookeeper:
#      connect-string: 192.168.163.210:2181
server:
  port: 8082