server:
  port: 0
spring:
  profiles:
    active: rabbit
debug: false

---
spring:
  profiles: rabbit
  cloud:
    stream:
      bindings:
        sink :
         destination: transformedRabbit
         binder: rabbit
         group: transformedText

      rabbit:
        binder:
#          nodes: 192.168.163.210
        bindings:
          sink:
            consumer:
              durableSubscription: true
              declareExchange: true
              exchangeDurable: true
              exchangeType: topic
  rabbitmq:
    host: localhost
#    password: rabbitmq
#    username: rabbitmq

---
spring:
  profiles: kafka
  cloud:
    stream:
      bindings:
        sink :
         destination: transformedKafka
         binder: kafka
         group: transformedText
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
          defaultZkPort: 2181
          offsetUpdateTimeWindow: 0
          autoCreateTopics: true
          autoAddPartitions: true
          minPartitionCount: 2
          replicationFactor: 1
        consumer:
          autoRebalanceEnabled: false
          autoCommitOffset: false
          startOffset: earliest
#  kafka:
#    bootstrap-servers: 192.168.163.210:9092
#    zookeeper:
#      connect-string: 192.168.163.210:2181

---
spring:
  profiles: artemis
  cloud:
    stream:
      bindings:

        sink:
         destination: jms.queue.transformedArtemis
         binder: artemis
         group: transformedText
#         consumer:
#           partitioned: true
#           concurrency: 1

      artemis:
        binder:
          transport: org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnectorFactory

  artemis:
    mode: native
    host: localhost
    user: user
    password: password
    port: 61616